using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CardsAgainstHumanity.DatabaseAccess.Entities.Configuration;

public class CardConfig : IEntityTypeConfiguration<Card> {
    public void Configure(EntityTypeBuilder<Card> builder) {
        builder
            .HasOne(child => child.User)
            .WithMany(parent => parent.Cards)
            .HasForeignKey(child => child.UserId)
            .OnDelete(DeleteBehavior.NoAction);

        builder.Property(e => e.Text)
            .HasColumnType("nvarchar(256)");

        builder.Property(e => e.Language)
            .HasColumnType("nvarchar(32)")
            .HasConversion<string>(
                e => e.ToString(),
                e => (Language)Enum.Parse(typeof(Language), e)
            );

        builder.Property(e => e.Type)
            .HasColumnType("nchar(5)")
            .HasConversion<string>(
                e => e.ToString(),
                e => (CardType)Enum.Parse(typeof(CardType), e)
            );

        if(Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") == "Development") {
            builder.HasData(
                new Card { Id = 1, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "____? There's an app for that" },
                new Card { Id = 2, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "Why can't I sleep at night? ____" },
                new Card { Id = 3, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "What's that smell? ____" },
                new Card { Id = 4, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "I got 99 problems but ____ ain't one." },
                new Card { Id = 5, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "Who stole the cookies from the cookie jar? ____" },
                new Card { Id = 6, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "What's the next Happy Meal (r) toy? ____" },
                new Card { Id = 7, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "Anthropologists have recently discovered a primitive tribe that worships ____." },
                new Card { Id = 8, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "It's a pity that kids these days are all getting involved with ____." },
                new Card { Id = 9, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of ____." },
                new Card { Id = 10, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "Alternative medicine is now embracing the curative powers of ____." },
                new Card { Id = 11, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "And the Academy Award for ____ goes to ____." },
                new Card { Id = 12, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "What's that sound? ____" },
                new Card { Id = 13, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "What ended my last relationship? ____" },
                new Card { Id = 14, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "MTV's new reality TV show features eight washed-up celebrities living with ____." },
                new Card { Id = 15, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "I drink to forget ____." },
                new Card { Id = 16, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "I'm sorry, I couldn't complete my homework because of ____." },
                new Card { Id = 17, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "What is Batman's guilty pleasure? ____" },
                new Card { Id = 18, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "This is the way the world ends. Not with a bang but with ____." },
                new Card { Id = 19, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "What's a girl's best friend? ____" },
                new Card { Id = 20, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "TSA guidelines now prohibit ____ on airplanes." },
                new Card { Id = 21, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "____. That's how I want to die." },
                new Card { Id = 22, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "For my next trick, I will pull ____ out of ____." },
                new Card { Id = 23, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "In the new Disney Channel Original Movie, Hannah Montana struggles with ____ for the first time." },
                new Card { Id = 24, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "____ is a slippery slope that leads to ____." },
                new Card { Id = 25, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "What does Dick Cheney prefer? ____" },
                new Card { Id = 26, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "I wish I hadn't lost the instruction manual for ____." },
                new Card { Id = 27, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "Instead of coal, Santa now gives the bad children ____." },
                new Card { Id = 28, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "What's the most emo? ____" },
                new Card { Id = 29, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "In 1,000 years, when paper money is but a distant memory, ____ will be our currency." },
                new Card { Id = 30, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "What's the next superhero/sidekick duo? ____ ____" },
                new Card { Id = 31, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "In M. Night Shyamalan's new movie, Bruce Willis discovers that ____ had really been ____ all along" },
                new Card { Id = 32, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "A romantic, candlelit dinner would be incomplete without ____." },
                new Card { Id = 33, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "____. Betcha can't have just one!" },
                new Card { Id = 34, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "White people like ____." },
                new Card { Id = 35, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "____. High five, bro." },
                new Card { Id = 36, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "Next from J.K. Rowling: Harry Potter and Chamber of ____." },
                new Card { Id = 37, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "BILLY MAYS HERE FOR ____." },
                new Card { Id = 38, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "In a world ravaged by ____, our only solace is ____." },
                new Card { Id = 39, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "War! What is it good for? ____" },
                new Card { Id = 40, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "During sex, I like to think about ____." },
                new Card { Id = 41, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "What are my parents hiding from me? ____" },
                new Card { Id = 42, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "What will always get you laid? ____" },
                new Card { Id = 43, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "When I'm in prison, I'll have ____ smuggled in." },
                new Card { Id = 44, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "What did I bring back from Mexico? ____" },
                new Card { Id = 45, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "What don't you want to find in your Chinese food? ____" },
                new Card { Id = 46, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "What will I bring back in time to convince people that I am a powerful wizard? ____" },
                new Card { Id = 47, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "How am I maintaining my relationship status? ____" },
                new Card { Id = 48, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "Coming to Broadway this season, ____: The Musical." },
                new Card { Id = 49, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on ____." },
                new Card { Id = 50, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "After Hurricane Katrina, Sean Penn brought ____ to the people of New Orleans." },
                new Card { Id = 51, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "Due to a PR fiasco, Walmart no longer offers ____." },
                new Card { Id = 52, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "In his new summer comedy, Rob Schneider is ____ trapped in the body of ____." },
                new Card { Id = 53, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "Rumor has it that Vladimir Putin's favorite dish is ____ stuffed with ____." },
                new Card { Id = 54, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "But before I kill you Mr. Bond, I must show you ____." },
                new Card { Id = 55, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "What gives me uncontrollable gas? ____" },
                new Card { Id = 56, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "What do old people smell like? ____" },
                new Card { Id = 57, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "The class field trip was completely ruined by ____." },
                new Card { Id = 58, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "When Pharaoh remained unmoved, Moses called down a Plague of ____." },
                new Card { Id = 59, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "What's my secret power? ____" },
                new Card { Id = 60, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "what's there a ton of in heaven? ____" },
                new Card { Id = 61, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "What would grandma find disturbing, yet oddly charming? ____" },
                new Card { Id = 62, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "I never truly understood ____ until I encountered ____." },
                new Card { Id = 63, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "The US has begun airdropping ____ to the children of Afghanistan." },
                new Card { Id = 64, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "What helps Obama unwind? ____" },
                new Card { Id = 65, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "What did Vin Diesel eat for dinner? ____" },
                new Card { Id = 66, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "____: good to the last drop." },
                new Card { Id = 67, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "Why am I sticky? ____" },
                new Card { Id = 68, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "What gets better with age? ____" },
                new Card { Id = 69, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "____: kid-tested, mother-approved." },
                new Card { Id = 70, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "What's the crustiest? ____" },
                new Card { Id = 71, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "What's Teach for America using to inspire inner city students to succeed? ____" },
                new Card { Id = 72, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "Studies show that lab rats navigate mazes 50% faster after being exposed to ____." },
                new Card { Id = 73, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "Life was difficult for cavemen before ____." },
                new Card { Id = 74, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "Make a haiku. ____ ____ ____" },
                new Card { Id = 75, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "I do not know with what weapons World War III will be fought, but World War IV will be fought with ____." },
                new Card { Id = 76, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "Why do I hurt all over? ____" },
                new Card { Id = 77, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "What am I giving up for Lent? ____" },
                new Card { Id = 78, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "In Michael Jackson's final moments, he thought about ____." },
                new Card { Id = 79, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on ____." },
                new Card { Id = 80, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "When I am President of the United States, I will create the department of ____." },
                new Card { Id = 81, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "Lifetime (r) presents ____, the story of ____." },
                new Card { Id = 82, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "When I am a billionaire, I shall erect a 50-foot statue to commemorate ____." },
                new Card { Id = 83, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "When I was tripping on acid, ____ turned into ____." },
                new Card { Id = 84, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "That's right, I killed ____. How, you ask? ____." },
                new Card { Id = 85, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "What's my anti-drug? ____" },
                new Card { Id = 86, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "____ + ____ = ____." },
                new Card { Id = 87, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "What never fails to liven up the party? ____" },
                new Card { Id = 88, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "What's the new fad diet? ____" },
                new Card { Id = 89, UserId = 1, Language = Language.English, Type = CardType.Black, Text = "Major League Baseball has banned ____ for giving players an unfair advantage." },
                new Card { Id = 90, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Coat hanger abortions" },
                new Card { Id = 91, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Man meat" },
                new Card { Id = 92, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Autocannibalism" },
                new Card { Id = 93, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Vigorous jazz hands" },
                new Card { Id = 94, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Flightless birds" },
                new Card { Id = 95, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Pictures of boobs" },
                new Card { Id = 96, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Doing the right thing" },
                new Card { Id = 97, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Hunting accidents" },
                new Card { Id = 98, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A cartoon camel enjoying the smooth, refreshing taste of a cigarette" },
                new Card { Id = 99, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The violation of our most basic human rights" },
                new Card { Id = 100, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Viagra (r)" },
                new Card { Id = 101, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Self-loathing" },
                new Card { Id = 102, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Spectacular abs" },
                new Card { Id = 103, UserId = 1, Language = Language.English, Type = CardType.White, Text = "An honest cop with nothing left to lose" },
                new Card { Id = 104, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Abstinence" },
                new Card { Id = 105, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A balanced breakfast" },
                new Card { Id = 106, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Mountain Dew Code Red" },
                new Card { Id = 107, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Concealing a boner" },
                new Card { Id = 108, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Roofies" },
                new Card { Id = 109, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Glenn Beck convulsively vomiting as a brood of crab spiders hatches in his brain and erupts from his tear ducts" },
                new Card { Id = 110, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Tweeting" },
                new Card { Id = 111, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The Big Bang" },
                new Card { Id = 112, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Amputees" },
                new Card { Id = 113, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Dr. Martin Luther King, Jr." },
                new Card { Id = 114, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Former President George W. Bush" },
                new Card { Id = 115, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Being marginalized" },
                new Card { Id = 116, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Smegma" },
                new Card { Id = 117, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Laying an egg" },
                new Card { Id = 118, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Cuddling" },
                new Card { Id = 119, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Aaron Burr" },
                new Card { Id = 120, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The Pope" },
                new Card { Id = 121, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A bleached asshole" },
                new Card { Id = 122, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Horse meat" },
                new Card { Id = 123, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Genital piercings" },
                new Card { Id = 124, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Fingering" },
                new Card { Id = 125, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Elderly Japanese men" },
                new Card { Id = 126, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Stranger danger" },
                new Card { Id = 127, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Fear itself" },
                new Card { Id = 128, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Science" },
                new Card { Id = 129, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Praying the gay away" },
                new Card { Id = 130, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Same-sex ice dancing" },
                new Card { Id = 131, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The terrorists" },
                new Card { Id = 132, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Making sex at here" },
                new Card { Id = 133, UserId = 1, Language = Language.English, Type = CardType.White, Text = "German dungeon porn" },
                new Card { Id = 134, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Bingeing and purging" },
                new Card { Id = 135, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Ethnic cleansing" },
                new Card { Id = 136, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Cheating in the Special Olympics" },
                new Card { Id = 137, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Nickelback" },
                new Card { Id = 138, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Heteronormativity" },
                new Card { Id = 139, UserId = 1, Language = Language.English, Type = CardType.White, Text = "William Shatner" },
                new Card { Id = 140, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Making a pouty face" },
                new Card { Id = 141, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Chainsaws for hands" },
                new Card { Id = 142, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The placenta" },
                new Card { Id = 143, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The profoundly handicapped" },
                new Card { Id = 144, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Tom Cruise" },
                new Card { Id = 145, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Object permanence" },
                new Card { Id = 146, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Goblins" },
                new Card { Id = 147, UserId = 1, Language = Language.English, Type = CardType.White, Text = "An icepick lobotomy" },
                new Card { Id = 148, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Arnold Schwarzenegger" },
                new Card { Id = 149, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Hormone injections" },
                new Card { Id = 150, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A falcon with a cap on its head" },
                new Card { Id = 151, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Foreskin" },
                new Card { Id = 152, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Dying" },
                new Card { Id = 153, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Stunt doubles" },
                new Card { Id = 154, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The invisible hand" },
                new Card { Id = 155, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Jew-fros" },
                new Card { Id = 156, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A really cool hat" },
                new Card { Id = 157, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Flash flooding" },
                new Card { Id = 158, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Flavored condoms" },
                new Card { Id = 159, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Dying of dysyntery" },
                new Card { Id = 160, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Sexy pillow fights" },
                new Card { Id = 161, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The Three-Fifths compromise" },
                new Card { Id = 162, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A sad handjob" },
                new Card { Id = 163, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Men" },
                new Card { Id = 164, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Historically black colleges" },
                new Card { Id = 165, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Sean Penn" },
                new Card { Id = 166, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Heartwarming orphans" },
                new Card { Id = 167, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Waterboarding" },
                new Card { Id = 168, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The clitoris" },
                new Card { Id = 169, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Vikings" },
                new Card { Id = 170, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Friends who eat all the snacks" },
                new Card { Id = 171, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The Underground Railroad" },
                new Card { Id = 172, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Pretending to care" },
                new Card { Id = 173, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Raptor attacks" },
                new Card { Id = 174, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A micropenis" },
                new Card { Id = 175, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A Gypsy curse" },
                new Card { Id = 176, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Agriculture" },
                new Card { Id = 177, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Bling" },
                new Card { Id = 178, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A clandestine butt scratch" },
                new Card { Id = 179, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The South" },
                new Card { Id = 180, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Sniffing glue" },
                new Card { Id = 181, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Consultants" },
                new Card { Id = 182, UserId = 1, Language = Language.English, Type = CardType.White, Text = "My humps" },
                new Card { Id = 183, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Geese" },
                new Card { Id = 184, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Being a dick to children" },
                new Card { Id = 185, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Party poopers" },
                new Card { Id = 186, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Sunshine and rainbows" },
                new Card { Id = 187, UserId = 1, Language = Language.English, Type = CardType.White, Text = "YOU MUST CONSTRUCT ADDITIONAL PYLONS" },
                new Card { Id = 188, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Mutually-assured destruction" },
                new Card { Id = 189, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Heath Ledger" },
                new Card { Id = 190, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Sexting" },
                new Card { Id = 191, UserId = 1, Language = Language.English, Type = CardType.White, Text = "An Oedipus complex" },
                new Card { Id = 192, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Eating all of the cookies before the AIDS bake-sale" },
                new Card { Id = 193, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A sausage festival" },
                new Card { Id = 194, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Michael Jackson" },
                new Card { Id = 195, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Skeletor" },
                new Card { Id = 196, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Chivalry" },
                new Card { Id = 197, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Sharing needles" },
                new Card { Id = 198, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Being rich" },
                new Card { Id = 199, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Muzzy" },
                new Card { Id = 200, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Count Chocula" },
                new Card { Id = 201, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Spontaneous human combustion" },
                new Card { Id = 202, UserId = 1, Language = Language.English, Type = CardType.White, Text = "College" },
                new Card { Id = 203, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Necrophilia" },
                new Card { Id = 204, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The Chinese gymnastics team" },
                new Card { Id = 205, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Global warming" },
                new Card { Id = 206, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Farting and walking away" },
                new Card { Id = 207, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Emotions" },
                new Card { Id = 208, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Uppercuts" },
                new Card { Id = 209, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Cookie Monster devouring the Eucharist wafers" },
                new Card { Id = 210, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Stifling a iggle at the mention of Hutus and Tutsis" },
                new Card { Id = 211, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Penis envy" },
                new Card { Id = 212, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Letting yourself go" },
                new Card { Id = 213, UserId = 1, Language = Language.English, Type = CardType.White, Text = "White people" },
                new Card { Id = 214, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Dick Cheney" },
                new Card { Id = 215, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Leaving an awkward voicemail" },
                new Card { Id = 216, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Yeast" },
                new Card { Id = 217, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Natural selection" },
                new Card { Id = 218, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Masturbation" },
                new Card { Id = 219, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Twinkies (r)" },
                new Card { Id = 220, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A LAN Party" },
                new Card { Id = 221, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Opposable thumbs" },
                new Card { Id = 222, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A grande sugar-free iced soy caramel macchiato" },
                new Card { Id = 223, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Soiling oneself" },
                new Card { Id = 224, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A sassy black woman" },
                new Card { Id = 225, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Sperm whales" },
                new Card { Id = 226, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Teaching a robot to love" },
                new Card { Id = 227, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Scrubbing under the folds" },
                new Card { Id = 228, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A drive-by shooting" },
                new Card { Id = 229, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Whipping it out" },
                new Card { Id = 230, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Panda sex" },
                new Card { Id = 231, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Catapults" },
                new Card { Id = 232, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Will Smith" },
                new Card { Id = 233, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Toni Morrison's vagina" },
                new Card { Id = 234, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Five-Dollar Foot-longs (tm)" },
                new Card { Id = 235, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Land minds" },
                new Card { Id = 236, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A sea of troubles" },
                new Card { Id = 237, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A zesty breakfast burrito" },
                new Card { Id = 238, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Christopher Walken" },
                new Card { Id = 239, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Friction" },
                new Card { Id = 240, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Balls" },
                new Card { Id = 241, UserId = 1, Language = Language.English, Type = CardType.White, Text = "AIDS" },
                new Card { Id = 242, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The KKK" },
                new Card { Id = 243, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Figgy pudding" },
                new Card { Id = 244, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Seppuku" },
                new Card { Id = 245, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Marky Mark and the Funky Bunch" },
                new Card { Id = 246, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Gandhi" },
                new Card { Id = 247, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Dave Matthews Band" },
                new Card { Id = 248, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Preteens" },
                new Card { Id = 249, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The token minority" },
                new Card { Id = 250, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Friends with benefits" },
                new Card { Id = 251, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Re-gifting" },
                new Card { Id = 252, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Pixelated bukkake" },
                new Card { Id = 253, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Substitute teachers" },
                new Card { Id = 254, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Take-backsies" },
                new Card { Id = 255, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A thermonuclear detonation" },
                new Card { Id = 256, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The Tempur-Pedic (r) Swedish Sleep System (tm)" },
                new Card { Id = 257, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Waiting 'til marriage" },
                new Card { Id = 258, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A tiny horse" },
                new Card { Id = 259, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A can of whoop-ass" },
                new Card { Id = 260, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Dental dams" },
                new Card { Id = 261, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Feeding Rosie O'Donnell" },
                new Card { Id = 262, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Old-people smell" },
                new Card { Id = 263, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Genghis Khan" },
                new Card { Id = 264, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Authentic Mexican cuisine" },
                new Card { Id = 265, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Oversized lollipops" },
                new Card { Id = 266, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Garth Brooks" },
                new Card { Id = 267, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Keanu Reeves" },
                new Card { Id = 268, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Drinking alone" },
                new Card { Id = 269, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The American Dream" },
                new Card { Id = 270, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Taking off your shirt" },
                new Card { Id = 271, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Giving 110%" },
                new Card { Id = 272, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Flesh-eating bacteria" },
                new Card { Id = 273, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Child abuse" },
                new Card { Id = 274, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A cooler full of organs" },
                new Card { Id = 275, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A moment of silence" },
                new Card { Id = 276, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The Rapture" },
                new Card { Id = 277, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Keeping Christ in Christmas" },
                new Card { Id = 278, UserId = 1, Language = Language.English, Type = CardType.White, Text = "RoboCop" },
                new Card { Id = 279, UserId = 1, Language = Language.English, Type = CardType.White, Text = "That one gay Teletubby" },
                new Card { Id = 280, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Sweet, sweet vengeance" },
                new Card { Id = 281, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Fancy Feast (r)" },
                new Card { Id = 282, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Pooping back and forth. Forever." },
                new Card { Id = 283, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Being a motherfucking sorcerer" },
                new Card { Id = 284, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Jewish fraternities" },
                new Card { Id = 285, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Edible underpants" },
                new Card { Id = 286, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Poor people" },
                new Card { Id = 287, UserId = 1, Language = Language.English, Type = CardType.White, Text = "All-you-can-eat shrimp for $4.99" },
                new Card { Id = 288, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Britney Spears at 55" },
                new Card { Id = 289, UserId = 1, Language = Language.English, Type = CardType.White, Text = "That thing that electrocutes your abs" },
                new Card { Id = 290, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The folly of man" },
                new Card { Id = 291, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Fiery poops" },
                new Card { Id = 292, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Cards Against Humanity" },
                new Card { Id = 293, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A murder most foul" },
                new Card { Id = 294, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Me time" },
                new Card { Id = 295, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The inevitable heat death of the universe" },
                new Card { Id = 296, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Nocturnal emissions" },
                new Card { Id = 297, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Daddy issues" },
                new Card { Id = 298, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The hardworking Mexican" },
                new Card { Id = 299, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Natalie Portman" },
                new Card { Id = 300, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Waking up half-naked in a Denny's parking lot" },
                new Card { Id = 301, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Nipple blades" },
                new Card { Id = 302, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Assless chaps" },
                new Card { Id = 303, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Full frontal nudity" },
                new Card { Id = 304, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Hulk Hogan" },
                new Card { Id = 305, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Passive-aggression" },
                new Card { Id = 306, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Ronald Reagan" },
                new Card { Id = 307, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Vehicular manslaughter" },
                new Card { Id = 308, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Menstruation" },
                new Card { Id = 309, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Pulling out" },
                new Card { Id = 310, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Picking up girls at the abortion clinic" },
                new Card { Id = 311, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The homosexual agenda" },
                new Card { Id = 312, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The Holy Bible" },
                new Card { Id = 313, UserId = 1, Language = Language.English, Type = CardType.White, Text = "World peace" },
                new Card { Id = 314, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Dropping a chandelier on your enemies and riding the rope up" },
                new Card { Id = 315, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Testicular torsion" },
                new Card { Id = 316, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The milk man" },
                new Card { Id = 317, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A time-travel paradox" },
                new Card { Id = 318, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Hot Pockets (r)" },
                new Card { Id = 319, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Guys who don't call" },
                new Card { Id = 320, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Eating the last known bison" },
                new Card { Id = 321, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Darth Vader" },
                new Card { Id = 322, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Scalping" },
                new Card { Id = 323, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Homeless people" },
                new Card { Id = 324, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The World of Warcraft" },
                new Card { Id = 325, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Gloryholes" },
                new Card { Id = 326, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Saxophone solos" },
                new Card { Id = 327, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Sean Connery" },
                new Card { Id = 328, UserId = 1, Language = Language.English, Type = CardType.White, Text = "God" },
                new Card { Id = 329, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Intelligent design" },
                new Card { Id = 330, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The taint; the grundle; the fleshy fun-bridge" },
                new Card { Id = 331, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Friendly fire" },
                new Card { Id = 332, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Keg stands" },
                new Card { Id = 333, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Eugenics" },
                new Card { Id = 334, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A good sniff" },
                new Card { Id = 335, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Lockjaw" },
                new Card { Id = 336, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A neglected Tamagotchi (tm)" },
                new Card { Id = 337, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The People's Elbow" },
                new Card { Id = 338, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Robert Downey, Jr." },
                new Card { Id = 339, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The heart of a child" },
                new Card { Id = 340, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Seduction" },
                new Card { Id = 341, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Smallpox blankets" },
                new Card { Id = 342, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Licking things to claim them as your own" },
                new Card { Id = 343, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A salty surprise" },
                new Card { Id = 344, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Poorly-timed Holocaust jokes" },
                new Card { Id = 345, UserId = 1, Language = Language.English, Type = CardType.White, Text = "My soul" },
                new Card { Id = 346, UserId = 1, Language = Language.English, Type = CardType.White, Text = "My sex life" },
                new Card { Id = 347, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Pterodactyl eggs" },
                new Card { Id = 348, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Altar boys" },
                new Card { Id = 349, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Forgetting the Alamo" },
                new Card { Id = 350, UserId = 1, Language = Language.English, Type = CardType.White, Text = "72 virgins" },
                new Card { Id = 351, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Raping and pillaging" },
                new Card { Id = 352, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Pedophiles" },
                new Card { Id = 353, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Eastern European Turbo-folk music" },
                new Card { Id = 354, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A snapping turtle biting the tip of your penis" },
                new Card { Id = 355, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Pabst Blue Ribbon" },
                new Card { Id = 356, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Domino's (tm) Oreo (tm) Dessert Pizza" },
                new Card { Id = 357, UserId = 1, Language = Language.English, Type = CardType.White, Text = "My collection of high-tech sex toys" },
                new Card { Id = 358, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A middle-aged man on roller skates" },
                new Card { Id = 359, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The Blood of Christ" },
                new Card { Id = 360, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Half-assed foreplay" },
                new Card { Id = 361, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Free samples" },
                new Card { Id = 362, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Douchebags on their iPhones" },
                new Card { Id = 363, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Hurricane Katrina" },
                new Card { Id = 364, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Wearing underwear inside-out to avoid doing laundry" },
                new Card { Id = 365, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Republicans" },
                new Card { Id = 366, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The glass ceiling" },
                new Card { Id = 367, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A foul mouth" },
                new Card { Id = 368, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Jerking off into a pool of children's tears" },
                new Card { Id = 369, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Getting really high" },
                new Card { Id = 370, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The deformed" },
                new Card { Id = 371, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Michelle Obama's arms" },
                new Card { Id = 372, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Explosions" },
                new Card { Id = 373, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The Übermensch" },
                new Card { Id = 374, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Donald Trump" },
                new Card { Id = 375, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Sarah Palin" },
                new Card { Id = 376, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Attitude" },
                new Card { Id = 377, UserId = 1, Language = Language.English, Type = CardType.White, Text = "This answer is postmodern" },
                new Card { Id = 378, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Crumpets with the Queen" },
                new Card { Id = 379, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Frolicking" },
                new Card { Id = 380, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Team-building exercises" },
                new Card { Id = 381, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Repression" },
                new Card { Id = 382, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Road head" },
                new Card { Id = 383, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A bag of magic beans" },
                new Card { Id = 384, UserId = 1, Language = Language.English, Type = CardType.White, Text = "An asymmetric boob job" },
                new Card { Id = 385, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Dead parents" },
                new Card { Id = 386, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Public ridicule" },
                new Card { Id = 387, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A mating display" },
                new Card { Id = 388, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A mime having a stroke" },
                new Card { Id = 389, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Stephen Hawking talking dirty" },
                new Card { Id = 390, UserId = 1, Language = Language.English, Type = CardType.White, Text = "African children" },
                new Card { Id = 391, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Mouth herpes" },
                new Card { Id = 392, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Overcompensation" },
                new Card { Id = 393, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Bill Nye the Science Guy" },
                new Card { Id = 394, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Bitches" },
                new Card { Id = 395, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Italians" },
                new Card { Id = 396, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Have some more kugel" },
                new Card { Id = 397, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A windmill full of corpses" },
                new Card { Id = 398, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Her Royal Highness, Queen Elizabeth II" },
                new Card { Id = 399, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Crippling debt" },
                new Card { Id = 400, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Adderall (tm)" },
                new Card { Id = 401, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A stray pube" },
                new Card { Id = 402, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Shorties and blunts" },
                new Card { Id = 403, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Passing a kidney stone" },
                new Card { Id = 404, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Prancing" },
                new Card { Id = 405, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Leprosy" },
                new Card { Id = 406, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A brain tumor" },
                new Card { Id = 407, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Bees?" },
                new Card { Id = 408, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Puppies!" },
                new Card { Id = 409, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Cockfights" },
                new Card { Id = 410, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Kim Jong-Il" },
                new Card { Id = 411, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Hope" },
                new Card { Id = 412, UserId = 1, Language = Language.English, Type = CardType.White, Text = "8 oz. of sweet Mexican black-tar heroin" },
                new Card { Id = 413, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Incest" },
                new Card { Id = 414, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Grave robbing" },
                new Card { Id = 415, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Asians who aren't good at math" },
                new Card { Id = 416, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Alcoholism" },
                new Card { Id = 417, UserId = 1, Language = Language.English, Type = CardType.White, Text = "(I am doing Kegels right now.)" },
                new Card { Id = 418, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Justin Bieber" },
                new Card { Id = 419, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The Jews" },
                new Card { Id = 420, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Bestiality" },
                new Card { Id = 421, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Winking at old people" },
                new Card { Id = 422, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Drum circles" },
                new Card { Id = 423, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Kids with ass cancer" },
                new Card { Id = 424, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Loose lips" },
                new Card { Id = 425, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Auschwitz" },
                new Card { Id = 426, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Civilian casualties" },
                new Card { Id = 427, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Inappropriate yodeling" },
                new Card { Id = 428, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Tangled Slinkys" },
                new Card { Id = 429, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Being on fire" },
                new Card { Id = 430, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The Thong Song" },
                new Card { Id = 431, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A vajazzled vagina" },
                new Card { Id = 432, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Riding off into the sunset" },
                new Card { Id = 433, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Exchanging pleasantries" },
                new Card { Id = 434, UserId = 1, Language = Language.English, Type = CardType.White, Text = "My relationship status" },
                new Card { Id = 435, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Shaquille O'Neals's acting career" },
                new Card { Id = 436, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Being fabulous" },
                new Card { Id = 437, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Lactation" },
                new Card { Id = 438, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Not reciprocating oral sex" },
                new Card { Id = 439, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Sobbing into a Hungry-Man (r) Frozen Dinner" },
                new Card { Id = 440, UserId = 1, Language = Language.English, Type = CardType.White, Text = "My genitals" },
                new Card { Id = 441, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Date rape" },
                new Card { Id = 442, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Ring Pops (tm)" },
                new Card { Id = 443, UserId = 1, Language = Language.English, Type = CardType.White, Text = "GoGurt" },
                new Card { Id = 444, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Judge Judy" },
                new Card { Id = 445, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Lumberjack fantasies" },
                new Card { Id = 446, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The gays" },
                new Card { Id = 447, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Scientology" },
                new Card { Id = 448, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Estrogen" },
                new Card { Id = 449, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Police brutality" },
                new Card { Id = 450, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Passable transvestites" },
                new Card { Id = 451, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The Virginia Tech Massacre" },
                new Card { Id = 452, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Tiger Woods" },
                new Card { Id = 453, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Dick fingers" },
                new Card { Id = 454, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Racism" },
                new Card { Id = 455, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Glenn Beck being harried by a swarm of buzzards" },
                new Card { Id = 456, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Surprise sex!" },
                new Card { Id = 457, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Classist undertones" },
                new Card { Id = 458, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Booby-trapping the house to foil burglars" },
                new Card { Id = 459, UserId = 1, Language = Language.English, Type = CardType.White, Text = "New Age music" },
                new Card { Id = 460, UserId = 1, Language = Language.English, Type = CardType.White, Text = "PCP" },
                new Card { Id = 461, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A lifetime of sadness" },
                new Card { Id = 462, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Doin' it in the butt" },
                new Card { Id = 463, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Swooping" },
                new Card { Id = 464, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The Hamburglar" },
                new Card { Id = 465, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Tentacle porn" },
                new Card { Id = 466, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A hot mess" },
                new Card { Id = 467, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Too much hair gel" },
                new Card { Id = 468, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A look-see" },
                new Card { Id = 469, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Not giving a shit about the Third World" },
                new Card { Id = 470, UserId = 1, Language = Language.English, Type = CardType.White, Text = "American Gladiators" },
                new Card { Id = 471, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The Kool-Aid man" },
                new Card { Id = 472, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Mr Snuffleupagus" },
                new Card { Id = 473, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Barack Obama" },
                new Card { Id = 474, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Golden showers" },
                new Card { Id = 475, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Wiping her butt" },
                new Card { Id = 476, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Queefing" },
                new Card { Id = 477, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Getting drunk on mouthwash" },
                new Card { Id = 478, UserId = 1, Language = Language.English, Type = CardType.White, Text = "An M. Night Shyamalan plot twist" },
                new Card { Id = 479, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A robust mongoloid" },
                new Card { Id = 480, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Nazis" },
                new Card { Id = 481, UserId = 1, Language = Language.English, Type = CardType.White, Text = "White privilege" },
                new Card { Id = 482, UserId = 1, Language = Language.English, Type = CardType.White, Text = "An erection that lasts longer than four hours" },
                new Card { Id = 483, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A disappointing birthday party" },
                new Card { Id = 484, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Puberty" },
                new Card { Id = 485, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Two midgets shitting in a bucket" },
                new Card { Id = 486, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Wifely duties" },
                new Card { Id = 487, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The forbidden fruit" },
                new Card { Id = 488, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Getting so angry that you pop a boner" },
                new Card { Id = 489, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Sexual tension" },
                new Card { Id = 490, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Third base" },
                new Card { Id = 491, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A gassy antelope" },
                new Card { Id = 492, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Those times when you get sand in your vagina" },
                new Card { Id = 493, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A Super Soaker (tm) full of cat pee" },
                new Card { Id = 494, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Muhammad (Praise Be Unto Him)" },
                new Card { Id = 495, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Racially-biased SAT questions" },
                new Card { Id = 496, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Porn stars" },
                new Card { Id = 497, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A fetus" },
                new Card { Id = 498, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Obesity" },
                new Card { Id = 499, UserId = 1, Language = Language.English, Type = CardType.White, Text = "When you fart and a little bit comes out" },
                new Card { Id = 500, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Oompa-Loompas" },
                new Card { Id = 501, UserId = 1, Language = Language.English, Type = CardType.White, Text = "BATMAN!!!" },
                new Card { Id = 502, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Black people" },
                new Card { Id = 503, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Tasteful sideboob" },
                new Card { Id = 504, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Hot people" },
                new Card { Id = 505, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Grandma" },
                new Card { Id = 506, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Copping a feel" },
                new Card { Id = 507, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The Trail of Tears" },
                new Card { Id = 508, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Famine" },
                new Card { Id = 509, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Finger painting" },
                new Card { Id = 510, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The miracle of childbirth" },
                new Card { Id = 511, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Goats eating cans" },
                new Card { Id = 512, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A monkey smoking a cigar" },
                new Card { Id = 513, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Faith healing" },
                new Card { Id = 514, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Parting the Red Sea" },
                new Card { Id = 515, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Dead babies" },
                new Card { Id = 516, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The Amish" },
                new Card { Id = 517, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Impotence" },
                new Card { Id = 518, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Child beauty pageants" },
                new Card { Id = 519, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Centaurs" },
                new Card { Id = 520, UserId = 1, Language = Language.English, Type = CardType.White, Text = "AXE Body Spray" },
                new Card { Id = 521, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Kanye West" },
                new Card { Id = 522, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Women's suffrage" },
                new Card { Id = 523, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Children on leashes" },
                new Card { Id = 524, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Harry Potter erotica" },
                new Card { Id = 525, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The Dance of the Sugar Plum Fairy" },
                new Card { Id = 526, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Lance Armstrong's missing testicle" },
                new Card { Id = 527, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Dwarf tossing" },
                new Card { Id = 528, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Mathletes" },
                new Card { Id = 529, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Lunchables (tm)" },
                new Card { Id = 530, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Women in yogurt commercials" },
                new Card { Id = 531, UserId = 1, Language = Language.English, Type = CardType.White, Text = "John Wilkes Booth" },
                new Card { Id = 532, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Powerful thighs" },
                new Card { Id = 533, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Mr. Clean, right behind you" },
                new Card { Id = 534, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Multiple stab wounds" },
                new Card { Id = 535, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Cybernetic enhancements" },
                new Card { Id = 536, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Serfdom" },
                new Card { Id = 537, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Another god-damn vampire movie" },
                new Card { Id = 538, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Glenn Beck catching his scrotum on a curtain hook" },
                new Card { Id = 539, UserId = 1, Language = Language.English, Type = CardType.White, Text = "A big hoopla about nothing" },
                new Card { Id = 540, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Peeing a little bit" },
                new Card { Id = 541, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The Hustle" },
                new Card { Id = 542, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Ghosts" },
                new Card { Id = 543, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Bananas in Pajamas" },
                new Card { Id = 544, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Active listening" },
                new Card { Id = 545, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Dry heaving" },
                new Card { Id = 546, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Kamikaze pilots" },
                new Card { Id = 547, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The Force" },
                new Card { Id = 548, UserId = 1, Language = Language.English, Type = CardType.White, Text = "Anal beads" },
                new Card { Id = 549, UserId = 1, Language = Language.English, Type = CardType.White, Text = "The Make-A-Wish (r) Foundation" }
            );
        }
    }
}
